version: '3.4'

services:
  identity.apigateway:
    image: ${DOCKER_REGISTRY-}identityapigateway
    build:
      context: .
      dockerfile: 02.Apigateways/Identity.ApiGateway/Dockerfile
    ports:
      - "5132:8080"
    depends_on:
      - identity.api

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: 03.Service/01.Identity/01.Identity.Api/Identity.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__EcommerceContext=Server=sqlserver;Database=EcommerceIdentity;User Id=sa;Password=Your_password123;TrustServerCertificate=True;
    ports:
      - "5015:8080"
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume:
